src/Entity/QueueTask.php
<?php

namespace App\Entity;

use App\Exception\QueueTaskException\StateSwitchException;
use App\Utilities\Enum\QueueTaskStatusEnum;
use App\Utilities\StateSwitch\QueueTaskStateSwitch;
use App\Utilities\Traits\TimeStamp;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass="App\Repository\QueueTaskRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"isActive", "queueNumber"},
 *     errorPath="queueNumber",
 *     message="This number is already in use."
 * )
 */
class QueueTask extends QueueTaskStateSwitch
{
    use TimeStamp;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\QueueTaskStatusLog", mappedBy="queueTask", orphanRemoval=true, cascade={"persist"})
     * @ORM\OrderBy({"id" = "DESC"})
     */
    private $statusList;

    /**
     * @ORM\Column(type="integer")
     */
    private $queueNumber;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\InterestType", inversedBy="queueTasks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $interestType;

    /**
     * @ORM\Column(type="boolean", options={"default" : 1})
     */
    private $isQueueNumberInUse=true;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\EmployeeDesk", mappedBy="queueTask", cascade={"persist", "remove"})
     */
    private $employeeDesk;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isComplete = false;

    public function __construct()
    {
        $this->statusList = new ArrayCollection();

        $this->setIsQueueNumberInUse(true);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFormattedQueueNumber(): ?string
    {
        if ($this->getQueueNumber() <= 9)
            return "{$this->getInterestType()->getId()}0{$this->getQueueNumber()}";
        else
            return "{$this->getInterestType()->getId()}{$this->getQueueNumber()}";
    }

    public function getQueueNumber(): ?int
    {
        return $this->queueNumber;
    }

    public function setQueueNumber(int $queueNumber): self
    {
        $this->queueNumber = $queueNumber;

        $this->isActive = true;

        return $this;
    }

    /**
     * @return Collection|QueueTaskStatusLog[]
     */
    public function getStatusList(): Collection
    {
        return $this->statusList;
    }

    public function addStatus($status,EmployeeDesk $employeeDesk = null, Employee $employee = null)
    {
        $statusObject = new QueueTaskStatusLog();

        $statusObject->setEmployee($employee);
        $statusObject->setEmployeeDesk($employeeDesk);

        if ($this->getNewestStatusList() === -1) {
            $statusObject->setStatus(QueueTaskStatusEnum::NEW);
            $this->addStatusList($statusObject);
            return $this;
        }

        if ($this->canSwitchState($this->getNewestStatusList(), $status)) {
            $statusObject->setStatus($status);
            $this->addStatusList($statusObject);
        } else {
//            throw new StateSwitchException();
        }

        return $this;
    }

    public function getNewestStatusList()
    {
        $statusObject = $this->statusList->first();

        if ($statusObject === false)
            return -1;
        else
            return $statusObject->getStatus();
    }

    public function addStatusList(QueueTaskStatusLog $statusList): self
    {
        $currentDate = new\DateTime('now');
        $statusList->setCreatedAt($currentDate->getTimestamp());

        if (!$this->statusList->contains($statusList)) {
            $this->statusList[] = $statusList;
            $statusList->setQueueTask($this);
        }

        if (in_array($statusList->getStatus(), QueueTaskStatusEnum::END)) {
            $this->isActive = false;
            $this->isComplete = true;
            $this->isQueueNumberInUse = false;
        }

        return $this;
    }

    public function removeStatusList(QueueTaskStatusLog $statusList): self
    {
        if ($this->statusList->contains($statusList)) {
            $this->statusList->removeElement($statusList);
            // set the owning side to null (unless already changed)
            if ($statusList->getQueueTask() === $this) {
                $statusList->setQueueTask(null);
            }
        }

        return $this;
    }

    public function getInterestType(): ?InterestType
    {
        return $this->interestType;
    }

    public function setInterestType(?InterestType $interestType): self
    {
        $this->interestType = $interestType;

        return $this;
    }

    public function getIsQueueNumberInUse(): ?bool
    {
        return $this->isQueueNumberInUse;
    }

    public function setIsQueueNumberInUse(bool $isQueueNumberInUse): self
    {
        $this->isQueueNumberInUse = $isQueueNumberInUse;

        return $this;
    }

    public function getEmployeeDesk(): ?EmployeeDesk
    {
        return $this->employeeDesk;
    }

    public function setEmployeeDesk(?EmployeeDesk $employeeDesk): self
    {
        $this->employeeDesk = $employeeDesk;

        // set (or unset) the owning side of the relation if necessary
        $newQueueTask = $employeeDesk === null ? null : $this;
        if ($newQueueTask !== $employeeDesk->getQueueTask()) {
            $employeeDesk->setQueueTask($newQueueTask);
        }

        return $this;
    }

    public function getIsComplete(): ?bool
    {
        return $this->isComplete;
    }

    public function setIsComplete(bool $isComplete): self
    {
        $this->isComplete = $isComplete;

        return $this;
    }
}

src/Controller/ActiveDeskController.php
<?php

namespace App\Controller;

use App\Entity\Employee;
use App\Entity\EmployeeDesk;
use App\Entity\QueueTask;
use App\Repository\EmployeeDeskRepository;
use App\Service\DeskAssigmentHelper;
use App\Utilities\Enum\QueueTaskStatusEnum;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ActiveDeskController
 * @package App\Controller
 */
class ActiveDeskController extends AbstractController
{

    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/active/desk", name="active_desk")
     */
    public function index(EmployeeDeskRepository  $employeeDeskRepository)
    {
        return $this->render('active_desk/list.html.twig', [
            'desks' => $employeeDeskRepository->findAll(),
        ]);
    }

    /**
     * @Route("/active/desk/{id}/occupy", name="active_desk_occupy")
     */
    public function occupyDesk(EmployeeDesk $employeeDesk)
    {
        /** @var Employee $employee */
        $employee = $this->getUser();

        if (null === $employeeDesk->getEmployee())
        {
            $employeeDesk->setEmployee($employee);

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('active_desk_dashboard',["id" => $employeeDesk->getId()]);
        }else{

            if ($employee === $employeeDesk->getEmployee())
            {
                return $this->redirectToRoute('active_desk_dashboard',["id" => $employeeDesk->getId()]);
            }

            $this->addFlash(
                'warning',
                'Stalas yra užimtas '
            );

            return $this->redirectToRoute('active_desk');
        }
    }

    /**
     * @Route("/active/desk/{id}/unoccupy", name="active_desk_unoccupy")
     */
    public function unOccupyDesk(EmployeeDesk $employeeDesk)
    {
        /** @var Employee $employee */
        $employee = $this->getUser();

        $employeeDesk->setEmployee(null);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('active_desk');
    }


    /**
     * @Route("/active/desk/{id}/dashboard", name="active_desk_dashboard")
     */
    public function manageDesk(EmployeeDesk $employeeDesk)
    {
        return $this->render('active_desk/index.html.twig', [
            'desk' => $employeeDesk,
            'queueTask' => $employeeDesk->getQueueTask()
        ]);
    }



    /**
     * @Route("/active/desk/{id}/completed", name="active_desk_complete_task")
     */
    public function completedTask(EmployeeDeskRepository $employeeDeskRepository,EmployeeDesk $employeeDesk, Request $request, DeskAssigmentHelper $deskAssigmentHelper)
    {
        $completed = $request->request->get('completed');

        if ($completed == QueueTaskStatusEnum::SOLVED) {
            $employeeDesk->getQueueTask()->addStatus(QueueTaskStatusEnum::SOLVED);
        }

        if ($completed == QueueTaskStatusEnum::UNSOLVABLE) {
            $employeeDesk->getQueueTask()->addStatus(QueueTaskStatusEnum::UNSOLVABLE);
        }

        if ($completed == QueueTaskStatusEnum::DENIED) {
            $employeeDesk->getQueueTask()->addStatus(QueueTaskStatusEnum::DENIED);
        }

        $this->entityManager->flush();
        $this->entityManager->clear();

        $array = [];
        /** @var QueueTask $queueTask */
        $queueTask = $deskAssigmentHelper->assignQueueTaskToDesk($employeeDesk, $employeeDesk->getEmployee()->getInterestType());

        if ($employeeDesk->getIsOnline()) {
            $desk = $employeeDeskRepository->findOneBy(['id'=>$employeeDesk->getId()]);
            $desk->setQueueTask($queueTask);
            $desk->setInUse(false);
            $this->entityManager->flush();
        } else {
            return new JsonResponse([
                $array = [
                    'in_use' => false,
                    'queue_task' => [
                        'number' => '',
                        'name' => '',
                        'status' => ''
                    ]
                ]
            ]);
        }

        return new JsonResponse([
            $this->returnFormattedQueueTask($queueTask)
        ]);
    }

    private function returnFormattedQueueTask($queueTask)
    {
        $array = array();

        if ($queueTask != null)
            $array = [
                'in_use' => true,
                'queue_task' => [
                    'number' => $queueTask->getFormattedQueueNumber(),
                    'name' => $queueTask->getInterestType()->getFullName(),
                    'status' => $queueTask->getStatusList()
                ]
            ];
        else
            $array = [
                'in_use' => true,
                'queue_task' => [
                    'number' => '',
                    'name' => '',
                    'status' => ''
                ]
            ];

        return $array;

    }

    /**
     * @Route("/active/desk/{id}/queue/task", name="active_desk_get_queue_task")
     */
    public function getQueueTask(EmployeeDesk $employeeDesk)
    {
        return new JsonResponse([
            $this->returnFormattedQueueTask($employeeDesk->getQueueTask())
        ]);
    }


    /**
     * @Route("/active/desk/{id}/toggle", name="active_desk_toggle")
     */
    public function toggleDesk(EmployeeDesk $employeeDesk, Request $request)
    {
        $toggle = ($request->request->get('toggle') == 'true')?true:false;

        $employeeDesk->setIsOnline($toggle);

        $this->entityManager->flush();

        return new JsonResponse(['toggle'=>$employeeDesk->getIsOnline()?"Taip":"Ne"]);
    }
}

templates/active_desk/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aktyvus stalas!{% endblock %}

{% block javascripts %}

    <script>

        $(document).ready(function () {
            requestUpdate();
            setInterval(requestUpdate,10000);
        });



        let toggle = {{ desk.isOnline|default('false') }};
        function toggleDesk() {

            $('#table-activation-button').toggleClass('btn-danger btn-success');
            toggleDeskRequest()
        }

        function toggleDeskRequest() {

            toggle = !toggle;
            let ajaxREFRESH = $.ajax({
                url: '{{ path('active_desk_toggle', {id: desk.id}) }}',
                type: 'POST',
                data: {toggle: toggle},
                dataType: 'json',
                async: false,
            });

            ajaxREFRESH.done(function (data) {
                console.log(data['toggle']);
                $('#online-label').html(data['toggle'].toString());
            }).fail(function () {

            });
        }

        function requestUpdate() {
            let ajaxREFRESH = $.ajax({
                url: '{{ path('active_desk_get_queue_task', {id: desk.id}) }}',
                type: 'POST',
                dataType: 'json',
                async: false,
            });

            ajaxREFRESH.done(function (data) {
                console.log(data[0])
                updateDashboard(data[0])
            }).fail(function () {
                console.log('Error');
            });
        }

        function updateDashboard(data) {
            $('#queue-number').html(data['queue_task']['number']);
            $('#interest-type').html(data['queue_task']['interest']);
        }

        function completedTask(status) {
            let ajaxCOMPLETED = $.ajax({
                url: '{{ path('active_desk_complete_task', {'id': desk.id } ) }}',
                type: 'POST',
                data: {completed: status},
                dataType: 'json',
                async: false,
            });

            ajaxCOMPLETED.done(function (data) {
                console.log(data[0])
                updateDashboard(data[0])
            }).fail(function () {
                console.log('Error');
            });
        }

    </script>

{% endblock %}

{% block body %}

    <style>
        th, td{
            vertical-align: middle !important;
            text-align: center !important;
        }

        .row .btn{
            width: 100%;
        }

    </style>


    <div class="container mt-5 pt-5">
        {#  General desk information  #}

        <table class="table">
            <tbody>
            <tr>
                <th>Ar stalas aktyvus: </th>
                <td><span id="online-label">{{ desk.isOnline?'Taip':'Ne' }}</span></td>
                <th>Stalo aktyvumo keitimas: </th>
                <td>
                    <button id="table-activation-button" class="btn btn-danger" onclick="toggleDesk()"> Aktyvus </button>
                </td>
            </tr>
            <tr>
                <th colspan="2">Dabartinis darbuotojas </th>
                <th colspan="1">{{desk.employee.firstname|default('Tuščia')}} {{desk.employee.lastname|default('')}} </th>
                <th colspan="1"> <a class="btn btn-danger" href="{{ path('active_desk_unoccupy', {'id': desk.id}) }}">Palikti stalą</a> </th>
            </tr>
            </tbody>
        </table>


        {#  Queue task information  #}

        <div>
            <h1 class="text-center py-2"> Užklausos tipas: <br> <span id="interest-type">{{ queueTask.interestType.fullName|default('Tuscia') }}</span></h1>
            <h3 class="text-center py-2 mb-4"> Laukimo numeris: <span id="queue-number">{{ queueTask.formattedQueueNumber|default('000') }}</span></h3>
        </div>

        <div class="row">
            <div class="col-4">
                <button id="solved-button" onclick="completedTask(4)" class="btn btn-success"> Išspręstas </button>
            </div>
            <div class="col-4">
                <button id="unsolved-button" onclick="completedTask(6)" class="btn btn-danger"> Neįmanoma išspręsti </button>
            </div>
            <div class="col-4">
                <button id="denied-button" onclick="completedTask(5)" class="btn btn-danger"> Atšaukas </button>
            </div>
        </div>


    </div>



{% endblock %}

templates/active_desk/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stalų sąrašas{% endblock %}

{% block body %}

    <style>
        td{
            vertical-align: middle !important;
            text-align: center !important;
        }
    </style>

    {% for label, flashes in app.session.flashbag.all %}
        {% for flash in flashes %}
            {% if ( label == 'success' ) %}
                <div class="alert alert-success alert-dismissible fade show">
                    {{ flash }}
                </div>
            {% elseif ( label == 'warning' ) %}
                <div class="alert alert-warning alert-dismissible fade show">
                    {{ flash }}
                </div>
            {% endif %}
        {% endfor %}
    {% endfor %}

    <div class="container">

        <div class="py-5">

            <h1 class="text-center mb-4">Stalų sąrašas</h1>

            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th>Id</th>
                    <th>Stalo numeris</th>
                    <th>Darbuotojas</th>
                    <th>Ar naudojamas ?</th>
                    <th>Ar aktyvus ?</th>
                    <th>Eilės numeris</th>
                    <th>Veiksmai</th>
                </tr>
                </thead>
                <tbody>
                {% for desk in desks %}
                    <tr>
                        <td>{{ desk.id }}</td>
                        <td>{{ desk.number }}</td>
                        <td>{{ desk.employee.firstName|default('') }} {{ desk.employee.lastName|default('') }}</td>
                        <td>{{ desk.inUse?"Tiesa":"Netiesa" }}</td>
                        <td>{{ desk.isOnline?"Tiesa":"Netiesa" }}</td>
                        <td>{{ desk.queueTask.formattedQueueNumber|default('') }}</td>
                        <td>
                                <a class="btn btn-primary d-block" href="{{ path('active_desk_occupy', {'id': desk.id}) }}">+</a>
                      </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="8">Nerasta duomenų</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}